version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - type: bind
        source: ./backend
        target: /app
        consistency: delegated  # or "cached"
      - /app/node_modules
    environment:
      - NODE_ENV=development
