version: "3.9"

services:
  backend:
    image: tomsabu444/capsave-backend:latest 
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
